manifest:
  defaults:
    remote: github

  remotes:
    - name: github
      url-base: https://github.com

  projects:
    - name: nrf
      remote: github
      repo-path: nrfconnect/sdk-nrf
      revision: v3.0.0-rc1
      path: nrf
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - libmodem
          - mbedtls
          - mcuboot
          - nanopb
          - nrfxlib
          - oberon-psa-crypto
          - picolibc
          - trusted-firmware-m
          - zephyr

  self:
    path: modules/thingsboard
