manifest:
  defaults:
    remote: github

  remotes:
    - name: github
      url-base: https://github.com

  projects:
    - name: nrf
      remote: github
      repo-path: nrfconnect/sdk-nrf
      revision: v3.0.0-rc1
      path: nrf
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - fatfs
          - hal_nordic
          - libmodem
          - littlefs
          - lz4
          - mbedtls
          - mcuboot
          - nanopb
          - net-tools
          - nrf-802154
          - nrf_hw_models
          - nrfxlib
          - oberon-psa-crypto
          - picolibc
          - segger
          - tinycrypt
          - trusted-firmware-m
          - zcbor
          - zephyr

  self:
    path: modules/thingsboard
