name: Build CI Docker Container

on:
  push:
    tags: 
    - 'docker/v*'
  pull_request:
    paths:
    - 'scripts/docker/**'

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker CI Container
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/sevenlab-de/thingboard-sdk-ci
        flavor: |
          latest=false
          suffix=-amd64
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Container
      id: build
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:scripts/docker"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}

    - name: Print size
      run: |
        docker images ${{ steps.build.imageid }} --format "{{.Repository}}:{{.Tag}} -> {{.Size}}"
