name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'samples/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'samples/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.27.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: thingsboard

      - name: Initialize
        run: |
          west init -l thingsboard
          west update -o=--depth=1 -n

      - name: Install Python Dependencies
        run: pip install -r thingsboard/scripts/requirements.txt

      - name: Twister Tests
        # bash is needed for source to be working
        shell: bash
        run: |
          source zephyr/zephyr-env.sh
          zephyr/scripts/twister -i -T thingsboard
